### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by xprimate** [himanshuagarwal190/ChatApp#1]
Hello, thanks for the git.

I am to send a message to the chat room after entering it, it no message dispalys.
The browser console is showing CORE error:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost:3000/socket.io/?EIO=3&transport=polling&t=NhZpgt9. (Reason: CORS request did not succeed).`

Kindly help.

**Comment by himanshuagarwal190** [comment]
Can you attach a screenshot? It is working fine for me when I send messages.

**Comment by xprimate** [comment]
Hello, here is the screen-shot
![Screenshot from 2021-07-27 06-01-53](https://user-images.githubusercontent.com/17166016/127098477-6b3a6aed-dade-45ef-988b-1bb58ac89585.png)
Also, I had to modify my socket url to localhost in chat.js
`...
const roomMessage = document.querySelector('.room-message');
const users = document.querySelector('.users');

//Socket server URL
const socket = io.connect('https://localhost:3000');`

**Comment by Ajithamilpur04** [comment]
same issue

**Comment by himanshuagarwal190** [comment]
There was a hardcoded url present. Now I have removed it. It should work now.
